"""add property_data phone_validation columns, retype enrichment_score

Revision ID: 44e41cd32ab5
Revises: e5a0851d63ec
Create Date: 2026-07-11 11:56:32.242726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44e41cd32ab5'
down_revision: Union[str, Sequence[str], None] = 'e5a0851d63ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('property_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('leads', sa.Column('phone_validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Postgres won't implicitly cast double precision -> varchar, so we have
    # to spell out the conversion (autogenerate can't infer this itself).
    op.alter_column('leads', 'enrichment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=10),
               existing_nullable=True,
               postgresql_using='enrichment_score::varchar(10)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'enrichment_score',
               existing_type=sa.String(length=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               postgresql_using='enrichment_score::double precision')
    op.drop_column('leads', 'phone_validation')
    op.drop_column('leads', 'property_data')
    # ### end Alembic commands ###
