"""add crm_idempotency_key to leads

Revision ID: 9c32d8b13a69
Revises: 44e41cd32ab5
Create Date: 2026-07-11 15:57:56.403064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c32d8b13a69'
down_revision: Union[str, Sequence[str], None] = '44e41cd32ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('crm_idempotency_key', sa.String(length=36), nullable=True))
    # Named explicitly (autogenerate left this unnamed) so downgrade() can
    # reference it - an unnamed constraint can't be dropped by name later.
    op.create_unique_constraint('uq_leads_crm_idempotency_key', 'leads', ['crm_idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_leads_crm_idempotency_key', 'leads', type_='unique')
    op.drop_column('leads', 'crm_idempotency_key')
    # ### end Alembic commands ###
