"""create leads, dead_letter_queue, circuit_breaker_state, enrichment_events

Revision ID: e5a0851d63ec
Revises: 
Create Date: 2026-07-05 15:13:04.763257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a0851d63ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_breaker_state',
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.Enum('closed', 'open', 'half_open', name='circuit_state'), server_default='closed', nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('service_name')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('property_address', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'enriching', 'enriched', 'failed', name='lead_status'), server_default='pending', nullable=False),
    sa.Column('enrichment_score', sa.Float(), nullable=True),
    sa.Column('personalized_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrichment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrichment_events')
    op.drop_table('dead_letter_queue')
    op.drop_table('leads')
    op.drop_table('circuit_breaker_state')
    # ### end Alembic commands ###

    # Manually added: Postgres ENUM types are separate database objects from
    # the column/table that uses them, so dropping the tables above does NOT
    # drop these types. Without this, running "upgrade" again after this
    # downgrade would fail with "type ... already exists".
    sa.Enum(name='lead_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='circuit_state').drop(op.get_bind(), checkfirst=True)
